//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.medio_pago_facturas = new HashSet<medio_pago_facturas>();
            this.producto_facturas = new HashSet<producto_facturas>();
        }
    
        public int id_factura { get; set; }
        public Nullable<System.DateTime> fecha_facturacion { get; set; }
        public Nullable<int> codigo_factura { get; set; }
        public string despachador { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_tienda { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tienda tienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medio_pago_facturas> medio_pago_facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_facturas> producto_facturas { get; set; }
    }
}
