//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class medio_pago_facturas
    {
        public int id_medio_pago_factura { get; set; }
        public Nullable<int> id_medios_pago { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> valor { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual medios_pagos medios_pagos { get; set; }
    }
}
