//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_facturas
    {
        public int id_producto_factura { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> precio_unitario { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
    }
}
